name: Build docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: standardese
          python-version: 3.8
          channels: conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      - name: Test push
        run: |
            conda install standardese
            standardese -V
