name: Build docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs
      - name: Test push
        run: |
            date > main/date.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A
            git commit -m "updated date"
            git push
